import * as React from 'react';
import ScrollToTop from './ScrollToTop';

const TermsOfService: React.FC<{ onBack: () => void }> = ({ onBack }) => {
  return (
    <div className="bg-white min-h-screen text-slate-800">
      <ScrollToTop />
      <div className="max-w-4xl mx-auto px-4 py-12">
        <button onClick={onBack} className="text-accent hover:underline mb-8 font-medium">
          &larr; Back to Dashboard
        </button>
        <h1 className="text-4xl font-bold mb-6 text-slate-900">Terms of Service</h1>
        <p className="text-sm text-slate-500 mb-8">Last Updated: {new Date().toLocaleDateString()}</p>
        
        <div className="prose prose-slate max-w-none space-y-6">
          <section>
            <h2 className="text-2xl font-semibold text-slate-900 mb-3">1. Acceptance of Terms</h2>
            <p>
              By accessing and using ComplyGuard AI, you agree to be bound by these Terms of Service. If you do not agree to these terms, please do not use our service.
            </p>
          </section>

          <section className="bg-blue-50 border-l-4 border-blue-500 p-4 rounded-r-lg">
            <h2 className="text-lg font-bold text-blue-900 mb-2">2. Not Legal Advice Disclaimer</h2>
            <p className="text-blue-800">
              <strong>ComplyGuard AI is an automated software tool, not a law firm.</strong> The gap analysis, remediation advice, and reports generated by our platform are for informational purposes only and do not constitute legal advice or guarantee regulatory compliance. You should consult with qualified legal counsel regarding your specific compliance obligations.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-slate-900 mb-3">3. User Responsibilities</h2>
            <p>
              You are responsible for maintaining the confidentiality of your account credentials and for all activities that occur under your account. You agree not to upload any documents that contain classified government information, illegal content, or malware.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-slate-900 mb-3">4. Subscription and Billing</h2>
            <p>
              Certain features require a paid subscription. Subscription fees are billed in advance on a recurring monthly or annual basis depending on your plan. All fees are non-refundable except where required by law.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-slate-900 mb-3">5. Limitation of Liability</h2>
            <p>
              To the maximum extent permitted by law, ComplyGuard AI and its affiliates shall not be liable for any indirect, incidental, special, consequential, or punitive damages resulting from your use of or inability to use the service, including any fines or penalties levied by regulatory authorities.
            </p>
          </section>
        </div>
      </div>
    </div>
  );
};

export default TermsOfService;
